services:
  nginx:  
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx

  market_hall_front:
    build: .
    container_name: market_hall_front
    ports:
      - "5173:5173"
    networks:
      - market_hall_network
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  market_hall_backend:
    build:
      context: ./../market_hall_backend/ 
    container_name: market_hall_backend 
    ports:
      - "5000:5000"
    networks:
      - market_hall_network 
    stdin_open: true
    tty: true
    volumes:
      - ./.volumes/instance/:/app/instance:rw
      - ./.volumes/uploads/:/app/uploads:rw

  market_hall_admin:
    build: 
      context: ./../market_hall_admin/
    container_name: market_hall_admin
    ports:
      - "4200:4200"
    networks:
      - market_hall_network  
    stdin_open: true
    tty: true    

  markethall_mail_api:
    build: 
      context: ./../markethall_mail_api/
      target: development 
    container_name: markethall_mail_api
    ports:
      - "8000:8000"
    networks:
      - market_hall_network  
    stdin_open: true
    tty: true    
  
networks:
  market_hall_network:  