events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://localhost:5173;
        } 
        location /../market_hall_backend {
            proxy_pass http://127.0.0.1:5000;
        } 
        location /../market_hall_admin {
            proxy_pass http://localhost:4200;
        }
        location /../markethall_mail_api {
            proxy_pass http://localhost:8200;
        }
        location /../markethall_payment_api {
            proxy_pass http://localhost:3000;
        }
    }
}