events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://localhost:5173;
        }

        location /../market_hall_backend {
            proxy_pass http://127.0.0.1:5000;
        }

         
    }
}